[features]
seeds = false
[programs.localnet]
staker = "7nerEma6QFA1WKrchArZhjn48q7buivNByLwHX9wHzQN"

[registry]
url = "https://api.apr.dev"

[provider]
# u can get ur own free cluster here: https://www.helius.dev
cluster = 'localnet'
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
